### ISSUE TITLE
Allow Branch Specification in .buildkite-ci-status.yml

### ISSUE THREAD

**Issue by ben-fletcher** [gencer/buildkite-ci-status#2]
I would like to be able to specify a specific branch in the `.buildkite-ci-status.yml` file instead of it just the latest build from any branch. 

E.g
```yaml
token: *******************
project: myproject
organization: myorganization
branch: master
```
